### ISSUE TITLE
No module named 'model.text_feature_extract'

### ISSUE THREAD

**Issue by ZYK100** [Suo-Wei/SRCF#2]
Hi, thanks for your sharing, i meet the following problem:

  File "src/train.py", line 8, in <module>
    from model.model import TextImgPersonReidNet
  File "/media/data/zyk10086/SRCF/src/model/model.py", line 6, in <module>
    from model.text_feature_extract import TextExtract
ModuleNotFoundError: No module named 'model.text_feature_extract'

**Comment by maxLWS** [comment]
> Hi, thanks for your sharing, i meet the following problem:
> 
> File "src/train.py", line 8, in from model.model import TextImgPersonReidNet File "/media/data/zyk10086/SRCF/src/model/model.py", line 6, in from model.text_feature_extract import TextExtract ModuleNotFoundError: No module named 'model.text_feature_extract'



> Hi, thanks for your sharing, i meet the following problem:
> 
> File "src/train.py", line 8, in from model.model import TextImgPersonReidNet File "/media/data/zyk10086/SRCF/src/model/model.py", line 6, in from model.text_feature_extract import TextExtract ModuleNotFoundError: No module named 'model.text_feature_extract'

Hi, I have tried to reproduce the code, just comment here.

**Comment by maxLWS** [comment]
> Hi, thanks for your sharing, i meet the following problem:
> 
> File "src/train.py", line 8, in from model.model import TextImgPersonReidNet File "/media/data/zyk10086/SRCF/src/model/model.py", line 6, in from model.text_feature_extract import TextExtract ModuleNotFoundError: No module named 'model.text_feature_extract'

Hi, just delete it

**Comment by ZYK100** [comment]
> > Hi, thanks for your sharing, i meet the following problem:
> > File "src/train.py", line 8, in from model.model import TextImgPersonReidNet File "/media/data/zyk10086/SRCF/src/model/model.py", line 6, in from model.text_feature_extract import TextExtract ModuleNotFoundError: No module named 'model.text_feature_extract'
> 
> Hi, just delete it

thank for your help!
i have solved this problem followed your comment. But i meet s new issue, can you help me?

Traceback (most recent call last):
  File "src/train.py", line 163, in <module>
    train(opt)
  File "src/train.py", line 83, in train
    for times, [image, label, caption_code, caption_length, caption_code_cr, caption_length_cr] in enumerate(train_dataloader):
  File "/home/ykzhang/anaconda3/envs/textreid/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/home/ykzhang/anaconda3/envs/textreid/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1085, in _next_data
    return self._process_data(data)
  File "/home/ykzhang/anaconda3/envs/textreid/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
    data.reraise()
  File "/home/ykzhang/anaconda3/envs/textreid/lib/python3.7/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/ykzhang/anaconda3/envs/textreid/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/ykzhang/anaconda3/envs/textreid/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ykzhang/anaconda3/envs/textreid/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/media/data/zyk10086/SRCF/src/data/dataset.py", line 218, in __getitem__
    examples=examples, seq_length=65, tokenizer=self.tokenizer)
  File "/media/data/zyk10086/SRCF/src/data/dataset.py", line 71, in convert_examples_to_features
    tokens_a = tokenizer.tokenize(example.text_a)
AttributeError: 'NoneType' object has no attribute 'tokenize'


It seems that "self.tokenizer = BertTokenizer.from_pretrained('saved_models/bert-base-uncased-vocab.txt', do_lower_case=True)" occurs an error. I have installed "pytorch_pretrained_bert". So how can i get "bert-base-uncased-vocab.txt".

**Comment by maxLWS** [comment]
> > > Hi, thanks for your sharing, i meet the following problem:
> > > File "src/train.py", line 8, in from model.model import TextImgPersonReidNet File "/media/data/zyk10086/SRCF/src/model/model.py", line 6, in from model.text_feature_extract import TextExtract ModuleNotFoundError: No module named 'model.text_feature_extract'

> > 
> > 
> > Hi, just delete it
> 
> thank for your help! i have solved this problem followed your comment. But i meet s new issue, can you help me?
> 
> Traceback (most recent call last): File "src/train.py", line 163, in train(opt) File "src/train.py", line 83, in train for times, [image, label, caption_code, caption_length, caption_code_cr, caption_length_cr] in enumerate(train_dataloader): File "/home/ykzhang/anaconda3/envs/textreid/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 435, in **next** data = self._next_data() File "/home/ykzhang/anaconda3/envs/textreid/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1085, in _next_data return self._process_data(data) File "/home/ykzhang/anaconda3/envs/textreid/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data data.reraise() File "/home/ykzhang/anaconda3/envs/textreid/lib/python3.7/site-packages/torch/_utils.py", line 428, in reraise raise self.exc_type(msg) AttributeError: Caught AttributeError in DataLoader worker process 0. Original Traceback (most recent call last): File "/home/ykzhang/anaconda3/envs/textreid/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop data = fetcher.fetch(index) File "/home/ykzhang/anaconda3/envs/textreid/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch data = [self.dataset[idx] for idx in possibly_batched_index] File "/home/ykzhang/anaconda3/envs/textreid/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in data = [self.dataset[idx] for idx in possibly_batched_index] File "/media/data/zyk10086/SRCF/src/data/dataset.py", line 218, in **getitem** examples=examples, seq_length=65, tokenizer=self.tokenizer) File "/media/data/zyk10086/SRCF/src/data/dataset.py", line 71, in convert_examples_to_features tokens_a = tokenizer.tokenize(example.text_a) AttributeError: 'NoneType' object has no attribute 'tokenize'
> 
> It seems that "self.tokenizer = BertTokenizer.from_pretrained('saved_models/bert-base-uncased-vocab.txt', do_lower_case=True)" occurs an error. I have installed "pytorch_pretrained_bert". So how can i get "bert-base-uncased-vocab.txt".



> > > 您好，感谢您的分享，我遇到了以下问题：
> > > 文件“src/train.py”，第 8 行，在 from model.model import TextImgPersonReidNet 文件“/media/data/zyk10086/SRCF/src/model/model.py "，第 6 行，在 from model.text_feature_extract import TextExtract ModuleNotFoundError: No module named 'model.text_feature_extract'
> > 
> > 
> > 你好，直接删除
> 
> 感谢您的帮助！ 我已经按照您的评论解决了这个问题。但是我遇到了新问题，你能帮帮我吗？
> 
> 回溯（最近调用最后一次）： 文件“src/train.py”，第 163 行，in train(opt) 文件“src/train.py”，第 83 行，in train for times，[image, label, caption_code, caption_length , caption_code_cr, caption_length_cr] in enumerate(train_dataloader): File "/home/ykzhang/anaconda3/envs/textreid/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 435, in **next** data = self._next_data() 文件“/home/ykzhang/anaconda3/envs/textreid/lib/python3.7/site-packages/torch/utils/data/dataloader.py”，第 1085 行，在 _next_data 返回 self._process_data （数据） 文件“/home/ykzhang/anaconda3/envs/textreid/lib/python3.7/site-packages/torch/utils/data/dataloader.py”，第 1111 行，在 _process_data data.reraise() 文件“/home/ykzhang/anaconda3/envs/textreid/lib/python3.7/site-packages/torch/_utils.py”，第 428 行，在 reraise raise self.exc_type(msg) AttributeError: Caught AttributeError in DataLoader worker process 0. 原始回溯（最近调用最后一次）： 文件“/home/ykzhang/anaconda3/envs/textreid/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py”，第 198 行，在 _worker_loop data = fetcher.fetch(index) 文件“/home/ykzhang/anaconda3/envs/textreid/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py​​”中，第 44 行， fetch data = [self.dataset[idx] for idx in possibly_batched_index] 文件“/home/ykzhang/anaconda3/envs/textreid/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py​​” , 第 44 行，在 data = [self.dataset[idx] for idx in possibly_batched_index] File "/media/data/zyk10086/SRCF/src/data/dataset.py", line 218, in **getitem** examples=examples, seq_length=65, tokenizer=self .tokenizer) 文件“/media/data/zyk10086/SRCF/src/data/dataset.py”，第 71 行，在 convert_examples_to_features tokens_a = tokenizer.tokenize(example.text_a) AttributeError: 'NoneType' 对象没有属性 'tokenize'
> 
> 似乎“self.tokenizer = BertTokenizer.from_pretrained('saved_models/bert-base-uncased-vocab.txt', do_lower_case=True)”发生错误。我已经安装了“pytorch_pretrained_bert”。那么我怎样才能得到“bert-base-uncased-vocab.txt”。



> > > Hi, thanks for your sharing, i meet the following problem:
> > > File "src/train.py", line 8, in from model.model import TextImgPersonReidNet File "/media/data/zyk10086/SRCF/src/model/model.py", line 6, in from model.text_feature_extract import TextExtract ModuleNotFoundError: No module named 'model.text_feature_extract'
> > 
> > 
> > Hi, just delete it
> 
> thank for your help! i have solved this problem followed your comment. But i meet s new issue, can you help me?
> 
> Traceback (most recent call last): File "src/train.py", line 163, in train(opt) File "src/train.py", line 83, in train for times, [image, label, caption_code, caption_length, caption_code_cr, caption_length_cr] in enumerate(train_dataloader): File "/home/ykzhang/anaconda3/envs/textreid/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 435, in **next** data = self._next_data() File "/home/ykzhang/anaconda3/envs/textreid/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1085, in _next_data return self._process_data(data) File "/home/ykzhang/anaconda3/envs/textreid/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data data.reraise() File "/home/ykzhang/anaconda3/envs/textreid/lib/python3.7/site-packages/torch/_utils.py", line 428, in reraise raise self.exc_type(msg) AttributeError: Caught AttributeError in DataLoader worker process 0. Original Traceback (most recent call last): File "/home/ykzhang/anaconda3/envs/textreid/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop data = fetcher.fetch(index) File "/home/ykzhang/anaconda3/envs/textreid/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch data = [self.dataset[idx] for idx in possibly_batched_index] File "/home/ykzhang/anaconda3/envs/textreid/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in data = [self.dataset[idx] for idx in possibly_batched_index] File "/media/data/zyk10086/SRCF/src/data/dataset.py", line 218, in **getitem** examples=examples, seq_length=65, tokenizer=self.tokenizer) File "/media/data/zyk10086/SRCF/src/data/dataset.py", line 71, in convert_examples_to_features tokens_a = tokenizer.tokenize(example.text_a) AttributeError: 'NoneType' object has no attribute 'tokenize'
> 
> It seems that "self.tokenizer = BertTokenizer.from_pretrained('saved_models/bert-base-uncased-vocab.txt', do_lower_case=True)" occurs an error. I have installed "pytorch_pretrained_bert". So how can i get "bert-base-uncased-vocab.txt".

Hi, maybe you can find it from https://huggingface.co/bert-base-uncased/tree/main

**Comment by ZYK100** [comment]
> > > > Hi, thanks for your sharing, i meet the following problem:
> > > > File "src/train.py", line 8, in from model.model import TextImgPersonReidNet File "/media/data/zyk10086/SRCF/src/model/model.py", line 6, in from model.text_feature_extract import TextExtract ModuleNotFoundError: No module named 'model.text_feature_extract'
> 
> > > Hi, just delete it
> > 
> > 
> > thank for your help! i have solved this problem followed your comment. But i meet s new issue, can you help me?
> > Traceback (most recent call last): File "src/train.py", line 163, in train(opt) File "src/train.py", line 83, in train for times, [image, label, caption_code, caption_length, caption_code_cr, caption_length_cr] in enumerate(train_dataloader): File "/home/ykzhang/anaconda3/envs/textreid/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 435, in **next** data = self._next_data() File "/home/ykzhang/anaconda3/envs/textreid/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1085, in _next_data return self._process_data(data) File "/home/ykzhang/anaconda3/envs/textreid/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data data.reraise() File "/home/ykzhang/anaconda3/envs/textreid/lib/python3.7/site-packages/torch/_utils.py", line 428, in reraise raise self.exc_type(msg) AttributeError: Caught AttributeError in DataLoader worker process 0. Original Traceback (most recent call last): File "/home/ykzhang/anaconda3/envs/textreid/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop data = fetcher.fetch(index) File "/home/ykzhang/anaconda3/envs/textreid/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch data = [self.dataset[idx] for idx in possibly_batched_index] File "/home/ykzhang/anaconda3/envs/textreid/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in data = [self.dataset[idx] for idx in possibly_batched_index] File "/media/data/zyk10086/SRCF/src/data/dataset.py", line 218, in **getitem** examples=examples, seq_length=65, tokenizer=self.tokenizer) File "/media/data/zyk10086/SRCF/src/data/dataset.py", line 71, in convert_examples_to_features tokens_a = tokenizer.tokenize(example.text_a) AttributeError: 'NoneType' object has no attribute 'tokenize'
> > It seems that "self.tokenizer = BertTokenizer.from_pretrained('saved_models/bert-base-uncased-vocab.txt', do_lower_case=True)" occurs an error. I have installed "pytorch_pretrained_bert". So how can i get "bert-base-uncased-vocab.txt".
> 
> > > > 您好，感谢您的分享，我遇到了以下问题：
> > > > 文件“src/train.py”，第 8 行，在 from model.model import TextImgPersonReidNet 文件“/media/data/zyk10086/SRCF/src/model/model.py "，第 6 行，在 from model.text_feature_extract import TextExtract ModuleNotFoundError: No module named 'model.text_feature_extract'
> > > 
> > > 
> > > 你好，直接删除
> > 
> > 
> > 感谢您的帮助！ 我已经按照您的评论解决了这个问题。但是我遇到了新问题，你能帮帮我吗？
> > 回溯（最近调用最后一次）： 文件“src/train.py”，第 163 行，in train(opt) 文件“src/train.py”，第 83 行，in train for times，[image, label, caption_code, caption_length , caption_code_cr, caption_length_cr] in enumerate(train_dataloader): File "/home/ykzhang/anaconda3/envs/textreid/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 435, in **next** data = self._next_data() 文件“/home/ykzhang/anaconda3/envs/textreid/lib/python3.7/site-packages/torch/utils/data/dataloader.py”，第 1085 行，在 _next_data 返回 self._process_data （数据） 文件“/home/ykzhang/anaconda3/envs/textreid/lib/python3.7/site-packages/torch/utils/data/dataloader.py”，第 1111 行，在 _process_data data.reraise() 文件“/home/ykzhang/anaconda3/envs/textreid/lib/python3.7/site-packages/torch/_utils.py”，第 428 行，在 reraise raise self.exc_type(msg) AttributeError: Caught AttributeError in DataLoader worker process 0. 原始回溯（最近调用最后一次）： 文件“/home/ykzhang/anaconda3/envs/textreid/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py”，第 198 行，在 _worker_loop data = fetcher.fetch(index) 文件“/home/ykzhang/anaconda3/envs/textreid/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py​​”中，第 44 行， fetch data = [self.dataset[idx] for idx in possibly_batched_index] 文件“/home/ykzhang/anaconda3/envs/textreid/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py​​” , 第 44 行，在 data = [self.dataset[idx] for idx in possibly_batched_index] File "/media/data/zyk10086/SRCF/src/data/dataset.py", line 218, in **getitem** examples=examples, seq_length=65, tokenizer=self .tokenizer) 文件“/media/data/zyk10086/SRCF/src/data/dataset.py”，第 71 行，在 convert_examples_to_features tokens_a = tokenizer.tokenize(example.text_a) AttributeError: 'NoneType' 对象没有属性 'tokenize'
> > 似乎“self.tokenizer = BertTokenizer.from_pretrained('saved_models/bert-base-uncased-vocab.txt', do_lower_case=True)”发生错误。我已经安装了“pytorch_pretrained_bert”。那么我怎样才能得到“bert-base-uncased-vocab.txt”。
> 
> > > > Hi, thanks for your sharing, i meet the following problem:
> > > > File "src/train.py", line 8, in from model.model import TextImgPersonReidNet File "/media/data/zyk10086/SRCF/src/model/model.py", line 6, in from model.text_feature_extract import TextExtract ModuleNotFoundError: No module named 'model.text_feature_extract'
> > > 
> > > 
> > > Hi, just delete it
> > 
> > 
> > thank for your help! i have solved this problem followed your comment. But i meet s new issue, can you help me?
> > Traceback (most recent call last): File "src/train.py", line 163, in train(opt) File "src/train.py", line 83, in train for times, [image, label, caption_code, caption_length, caption_code_cr, caption_length_cr] in enumerate(train_dataloader): File "/home/ykzhang/anaconda3/envs/textreid/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 435, in **next** data = self._next_data() File "/home/ykzhang/anaconda3/envs/textreid/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1085, in _next_data return self._process_data(data) File "/home/ykzhang/anaconda3/envs/textreid/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data data.reraise() File "/home/ykzhang/anaconda3/envs/textreid/lib/python3.7/site-packages/torch/_utils.py", line 428, in reraise raise self.exc_type(msg) AttributeError: Caught AttributeError in DataLoader worker process 0. Original Traceback (most recent call last): File "/home/ykzhang/anaconda3/envs/textreid/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop data = fetcher.fetch(index) File "/home/ykzhang/anaconda3/envs/textreid/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch data = [self.dataset[idx] for idx in possibly_batched_index] File "/home/ykzhang/anaconda3/envs/textreid/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in data = [self.dataset[idx] for idx in possibly_batched_index] File "/media/data/zyk10086/SRCF/src/data/dataset.py", line 218, in **getitem** examples=examples, seq_length=65, tokenizer=self.tokenizer) File "/media/data/zyk10086/SRCF/src/data/dataset.py", line 71, in convert_examples_to_features tokens_a = tokenizer.tokenize(example.text_a) AttributeError: 'NoneType' object has no attribute 'tokenize'
> > It seems that "self.tokenizer = BertTokenizer.from_pretrained('saved_models/bert-base-uncased-vocab.txt', do_lower_case=True)" occurs an error. I have installed "pytorch_pretrained_bert". So how can i get "bert-base-uncased-vocab.txt".
> 
> Hi, maybe you can find it from https://huggingface.co/bert-base-uncased/tree/main

Very thank you for your help!

**Comment by Suo-Wei** [comment]
If this bug has been solved, I will close the issue.
