### ISSUE TITLE
请问一下reid_raw.json您代码里为什么有个tokens字段，我下的数据集json里没有这个

### ISSUE THREAD

**Issue by huranLi** [Suo-Wei/SRCF#4]

**Comment by maxLWS** [comment]
请问能指出具体的代码位置吗，有可能并无影响

> _No description provided._

**Comment by maxLWS** [comment]
> _No description provided._

这个文件应该没有影响

**Comment by huranLi** [comment]
好的谢谢您



---原始邮件---
发件人: "Songwei ***@***.***&gt;
发送时间: 2023年4月1日(周六) 下午3:49
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Suo-Wei/SRCF] 请问一下reid_raw.json您代码里为什么有个tokens字段，我下的数据集json里没有这个 (Issue #4)




  
No description provided.
  
这个文件应该没有影响
