### ISSUE TITLE
saved_models/bert-base-uncased-vocab.txt was not found

### ISSUE THREAD

**Issue by lttkien1511** [Suo-Wei/SRCF#5]
![bertbasederror](https://github.com/Suo-Wei/SRCF/assets/86515602/9f49d4db-d47a-4481-b90b-6964c78e4235)
Hi, I have a problem like this when I run the command "bash run/train.bash". I have upgraded the transformers module to the latest version. 
 Does anyone help me with this problem?

**Comment by Suo-Wei** [comment]
because the transformers has been updated, you have to adjust the code in L-170 of model.py

**Comment by lttkien1511** [comment]
Do you mean this line?

model_class, tokenizer_class, pretrained_weights = (ppb.BertModel, ppb.BertTokenizer, 'bert-base-uncased')

Do you have any advice? I have no idea about it. Thank you very much.

**Comment by Suo-Wei** [comment]
yes, you have to adjust this line, because bert-base-uncased-vocab.txt has
been deprecated.   You can use the transformers and corresponding
pre-trained Bert to replace them. please refer to
https://huggingface.co/bert-base-uncased

lttkien1511 ***@***.***> 于2023年5月19日周五 01:46写道：

**Comment by lttkien1511** [comment]
Hi, I still cannot fix this problem. I found that I couldn't find the saved_models directory in this project. 

Moreover, I have added the line `from transformers import BertTokenizer, BertModel` and fix the line 170 in model.py into `model_class, tokenizer_class, pretrained_weights = (BertModel, BertTokenizer, 'bert_weight/bert-base-uncased')` but it still didn't work.

**Comment by Suo-Wei** [comment]
OK， maybe you can pip uninstall transformers and pip
install pytorch-pretrained-bert. And keep the original code.

   -





lttkien1511 ***@***.***> 于2023年5月21日周日 17:38写道：

**Comment by lttkien1511** [comment]
I have cloned your project and do again. And the problem is okay now.
